### ISSUE TITLE
Feature request, multiple selectors

### ISSUE THREAD

**Issue by anointed** [ahume/selector-queries#1]
Is it possible to have more than 2 selectors set via the parameters?

I'd like to have large, landscape, portrait, mobile, etc....

If not, I'd love to request the ability

**Comment by ahume** [comment]
Yes, you can set more than 2 class values on the element, so the following should work:

```
<div data-squery="max-width:800px=large max-width:600px=medium max-width:400px=small">
```

Is that what you mean?

**Comment by anointed** [comment]
AAAHHH SWEET, 
I actually tried something similar but had the syntax totally wrong. This is going to make a current project so much easier now.

Thank you!
